name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run black on files contained in the diff only
        run: |
          git diff --name-only --diff-filter=d "origin/$GITHUB_BASE_REF"..."origin/$GITHUB_HEAD_REF" | grep -E ".*\.py$" | xargs -r black --verbose
      - name: Push updates
        run: |
          git status --untracked=no
          git diff
          git add \*.py
          git commit -m "python black format fix"
          git push origin HEAD:$GITHUB_HEAD_REF
